# Generated by Django 5.1.2 on 2024-11-02 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication',
            old_name='user_id',
            new_name='user',
        ),
    ]
