# Generated by Django 5.1.2 on 2024-11-10 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0002_rename_user_id_medication_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medication',
        ),
    ]
