# Generated by Django 5.1.2 on 2024-11-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='health_card',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
